apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
  namespace: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-node
  template:
    metadata:
      labels:
        app: api-node
    spec:
      containers:
        - name: api-node
          image: vishesh3011/api-node
          env:
            - name: DATABASE_URL_FILE
              value: /etc/secrets/DATABASE_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: db-secret-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: db-secret-volume
          secret:
            secretName: db-secret